fix(ui): scale the doughnut chart with the font size
canonical-web-and-design/maas-ui pull request #1642
Opened 2020-09-16 01:32 UTC by huwshimi

## Done

- Update the doughnut chart to fit within its container.

## QA

### MAAS deployment

To run this branch you will need access to one of the following MAAS deployments:

- [Bolla](/HACKING.md#bolla)
- [A development MAAS](/HACKING.md#development-deployment)
- [A local snap MAAS](/HACKING.md#snap-deployment) (this will not usually have machines)

### Running the branch

You can run this branch by:

- Serving with [dotrun](/HACKING.md#maas-ui-development-setup)
- [Building in a development MAAS](/HACKING.md#running-maas-ui-from-a-development-maas)

### QA steps

- Navigate to a lxd pod details page that shows a doughnut chart.
- Change your browser's font size to something smaller than the default.
- The doughnut chart should resize and not overlap the content next to it.

## Fixes

Fixes: canonical-web-and-design/maas-ui#1588

2020-09-16 01:45 UTC, huwshimi commented on ui/src/app/base/components/DoughnutChart/DoughnutChart.tsx
> +  const id = useRef(`doughnut-chart-${nanoid()}`);
Drive-by to fix the id being updated on every render.

2020-09-16 01:45 UTC, huwshimi commented on ui/src/app/base/components/DoughnutChart/DoughnutChart.tsx
> -            transform={`xtranslate(${adjustedHoverWidth / 2}, ${
Drive-by to remove a disabled transform.

2020-09-18 01:12 UTC, Caleb-Ellis submitted a review, later dismissed
Nice! Looks good in FF and Chrome. :mag:

2020-09-18 01:15 UTC, Caleb-Ellis requested changes
Sorry, spoke too soon. The font-size bug is fixed, but the chart looks massive on smaller screens. Can we just set a max-width on the parent container?

![2020-09-18_11-14](https://user-images.githubusercontent.com/25733845/93543987-4111f180-f9a0-11ea-898d-9854387c9e48.png)
![2020-09-18_11-14_1](https://user-images.githubusercontent.com/25733845/93543989-43744b80-f9a0-11ea-9690-d16293ed8e61.png)

2020-09-18 02:27 UTC, huwshimi commented
> Sorry, spoke too soon. The font-size bug is fixed, but the chart looks massive on smaller screens. Can we just set a max-width on the parent container?
> 

Whoops, yep, fixed.

2020-09-18 04:12 UTC, Caleb-Ellis approved these changes
LGTM!

2020-09-18 04:27 UTC, merged