feat(ui): add status and cpu cards to machine details summary overview
canonical-web-and-design/maas-ui pull request #1833
Opened 2020-11-02 08:22 UTC by squidsoup

## Done

- add status and cpu cards to machine details summary overview

This branch was getting quite large, so `Memory` and `Storage` cards will be in follow-up branches.

## QA

### MAAS deployment

To run this branch you will need access to one of the following MAAS deployments:

- [Karura](/HACKING.md#karura)
- [Bolla](/HACKING.md#bolla)
- [A development MAAS](/HACKING.md#development-deployment)
- [A local snap MAAS](/HACKING.md#snap-deployment) (this will not usually have machines)

### Running the branch

You can run this branch by:

- Serving with [dotrun](/HACKING.md#maas-ui-development-setup)
- [Building in a development MAAS](/HACKING.md#running-maas-ui-from-a-development-maas)

### QA steps

- Ensure the status and cpu cards render as expected.
- Ensure links in the results list take you to the testing tab.
- With a machine with no tests run, ensure the "Test CPU..." link opens the testing take action button with the appropriate CPU tests selected.

## Fixes

Fixes: # .

## Launchpad issue

Related Launchpad maas issue in the form `lp#number`.

## Backports

In general, please propose fixes against *master* rather than release branches (e.g. 2.7), unless the fix is only applicable for that specific release. Please apply backport labels to the PR (e.g. "Backport 2.7") for the appropriate releases to target.

Only bug and security fixes should be backported, new features should only land in master.

2020-11-02 08:24 UTC, squidsoup commented on ui/src/app/machines/components/ActionFormWrapper/ActionFormWrapper.tsx
> +              hardwareType={selectedAction.hardwareType}
The `hardwareType` prop here feels right to me, as the `TestForm` can have different groups of tests selected depending on hardware, *however* I'm not entirely sure about setting `hardwareType` using `setSelectedAction`. Passing `setSelectedAction` down so many components I also don't love, but perhaps this just needs to be reworked later in redux. Any thoughts?

2020-11-03 02:13 UTC, Caleb-Ellis requested changes
A few bugs that should be addressed, and a couple of suggestions to move functions outside of components.

What do you think of this approach - we define a type in Machine.tsx:
``` ts
type SelectedAction = {
  name: MachineAction["name"];
  formProps?: [x: string]: any; // not sure how to type this one. Default = {}
};
```

Then in each of the Form components in `ActionFormWrapper` we spread `formProps`, e.g.
``` tsx
<DeployForm selectedAction={selectedAction.name} {...selectedAction.formProps} />
```

It's pretty much what you have, but generic.

2020-11-03 02:13 UTC, Caleb-Ellis commented on ui/src/app/machines/views/MachineDetails/MachineSummary/OverviewCard/StatusCard/StatusCard.tsx
> +          {`${machine.osystem}/${machine.distro_series}`}
There's a function in the MachineList code somewhere (maybe StatusCell?) that makes the machine OS a bit nicer, i.e. "ubuntu/focal" => "Ubuntu 20.04 LTS". Should probably use that here too.

2020-11-03 02:13 UTC, Caleb-Ellis commented on ui/src/app/machines/views/MachineDetails/MachineSummary/OverviewCard/_index.scss
> +@mixin pseudo-border($pos) {
This scss file is really not great. I'll definitely want to rewrite this once the overview card is finished content-wise, so I wouldn't worry too much about the styling.

2020-11-03 02:13 UTC, Caleb-Ellis commented on ui/src/app/store/general/types.ts
> +  hardwareType?: number;
I don't think this is the right approach. `MachineAction` here is returned from the server and will always have the top 4 properties. `hardwareType` is specific only to how it's being used in machine details, so should probably be a different type that lives there.

2020-11-03 02:13 UTC, Caleb-Ellis commented on ui/src/scss/_patterns_lists.scss
> +  .p-inline-list__item--compact {
Like I mentioned earlier, this can probably be removed.

2020-11-03 02:42 UTC, squidsoup commented on ui/src/app/machines/views/MachineDetails/MachineSummary/OverviewCard/StatusCard/StatusCard.tsx
> +  const isVM = machine.tags?.includes("virtual");
yep, added the additional code for powertype, nice catch thanks.

2020-11-04 01:13 UTC, Caleb-Ellis approved these changes
LGTM! Just one non-blocking comment.

Also I've added a card to make the KVM forms follow this same pattern, because at the moment it's sliiightly different. https://github.com/canonical-web-and-design/maas-ui/issues/1835

2020-11-04 01:13 UTC, Caleb-Ellis commented on ui/src/app/store/general/types.ts
> +  sentence?: string;
Do these still need to be optional if we're explicitly using `MachineAction["name"]` in the `SelectedAction` type?

2020-11-04 02:12 UTC, merged