use standard link variant in hardware sync tooltip
canonical-web-and-design/maas-ui pull request #3766
Opened 2022-04-05 08:00 UTC by petermakowski

## Done

- use a standard (blue) link variant in hardware sync tooltip
  - source: https://chat.canonical.com/canonical/pl/bk669n8wwfywudgtbmr11xtgph

## Screenshots
### Before
![image](https://user-images.githubusercontent.com/7452681/161706188-1896356b-cd6a-44a8-a22f-7d970d4396f8.png)

### After
![image](https://user-images.githubusercontent.com/7452681/161706207-bfc930ea-4c64-4c33-a5c7-9376c68011d1.png)

## QA

### MAAS deployment

To run this branch you will need access to one of the following MAAS deployments:

- [Karura](/HACKING.md#karura)
- [Bolla](/HACKING.md#bolla)
- [A development MAAS](/HACKING.md#development-deployment)
- [A local snap MAAS](/HACKING.md#snap-deployment) (this will not usually have machines)

### Running the branch

You can run this branch by:

- Serving with [dotrun](/HACKING.md#maas-ui-development-setup)
- [Building in a development MAAS](/HACKING.md#running-maas-ui-from-a-development-maas)

### QA steps

- Steps for QA.

## Fixes

Fixes: # .

## Launchpad issue

Related Launchpad maas issue in the form `lp#number`.

## Backports

In general, please propose fixes against *master* rather than release branches (e.g. 2.7), unless the fix is only applicable for that specific release. Please apply backport labels to the PR (e.g. "Backport 2.7") for the appropriate releases to target.

Only bug and security fixes should be backported, new features should only land in master.

2022-04-05 09:54 UTC, anthonydillon requested changes
Code is fine but surely we don't want to go backwards with accessibility so extremely?

![image](https://user-images.githubusercontent.com/1413534/161728741-dd65f40c-d986-4451-bb91-81707d6e96d4.png)

2022-04-05 10:17 UTC, petermakowski commented
> Code is fine but surely we don't want to go backwards with accessibility so extremely?

@anthonydillon you do have a point, and that's why I commented the original design suggesting using the inverted variant to fix the contrast.

This was initially agreed upon, but after further discussion @rayito [requested to revert this change](https://chat.canonical.com/canonical/pl/bk669n8wwfywudgtbmr11xtgph). I'm more than happy to keep this as is (in fact I'd prefer that as it's a better a11y), but we should all be on the same page this is what we want.

2022-04-05 10:32 UTC, rayito commented
The link colour is not correct. We have a link colour variant for dark backgrounds (and dark theme), as Lyubo mentioned in Mattermost it is not implemented yet in Vanilla so It would have to be done locally. See more here:

https://github.com/canonical-web-and-design/vanilla-framework/issues/3350#issuecomment-1072448352

However, the colour we have in Figma does not correspond with what we have in that issue. 

![image](https://user-images.githubusercontent.com/5860630/161734923-eb93b65a-0dc5-4135-b48a-ddb2ea3288de.png)

![image](https://user-images.githubusercontent.com/5860630/161735116-7f4f5b7f-dc58-43d3-800e-666bce5577b4.png)

@lyubomir-popov do you know which one is the final one? `#3097FF` or `#2E96FF`?

2022-04-05 17:47 UTC, lyubomir-popov commented
@rayito `3097FF` is the correct one.

2022-04-06 07:17 UTC, petermakowski commented
> @rayito `3097FF` is the correct one.

Thank you both. I'll update to use `#3097FF` locally until we get these changes to vanilla.

2022-04-07 08:38 UTC, anthonydillon approved these changes
LGTM :+1:

2022-04-07 09:13 UTC, merged